---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
    exclude_fingerprints:
    - d5d53f59247ba6952a3a2df1be0280bd
    - c229be8637ecd3f01d64af692cbf05eb
    checks:
      Rubocop/Rails/Output:
        enabled: false
ratings:
  paths:
  - "**.rb"
exclude_paths:
- spec/**/*
